server:
  port: 8082

spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: mongodb+srv://hotstar_dev:hotstar_dev@123@cluster0.owucl7h.mongodb.net/hotstar_catalog?appName=cluster0
    redis:
      url: rediss://default:AVjTAAIncDIxNmUzODE3NzVmMWM0YWJiODAwOTZjMDI0NDY3YjlkYnAyMjI3Mzk@alive-titmouse-22739.upstash.io:6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/